apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
spec:
  destination:
    name: ''
    namespace: sandbox
    server: 'https://kubernetes.default.svc'
  source:
    path: project/helm
    repoURL: 'https://github.com/aold619/nd064_course_1'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-prod.yaml
  project: default
